version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    expose:
      - "5000"
    environment:
      - APP_MESSAGE="Hello from Docker Compose!"
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:

